
<div class="inner">
	<ul class="nav-list-l1">
		<ul class="nav-list-l1">
			<li id="menu-item-6" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6"><a href="http://www.awesome-wordpress.loc/sample-page/">Sample Page</a></li>
			<li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8"><a href="http://www.awesome-wordpress.loc/sample-page/">Sample Page</a></li>
			<li id="menu-item-9" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-9"><a href="http://www.awesome-wordpress.loc/sample-page/">Sample Page</a></li>
			<li id="menu-item-10" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-10"><a href="http://www.awesome-wordpress.loc/sample-page/">Sample Page</a></li>
		</ul>
	</ul>
</div>